// Serve repository root on a dedicated test origin. Never run on a user's
// extension origin. Only this test's qa-* records are created or removed.
const output=document.querySelector('#results');let failures=0;
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
async function test(name,fn){const li=document.createElement('li');try{await fn();li.textContent='PASS · '+name;li.className='pass';}catch(error){failures++;li.textContent='FAIL · '+name+' · '+error.message;li.className='fail';console.error(error);}output.append(li);}
const request=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
const txDone=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error)});
const id='qa-evidence-workspace';
await test('Version 2 database upgrades without losing existing journeys',async()=>{
 const probe=await request(indexedDB.open('research-trail'));
 if(probe.version===1&&!probe.objectStoreNames.length){probe.close();await request(indexedDB.deleteDatabase('research-trail'));const req=indexedDB.open('research-trail',2);req.onupgradeneeded=()=>{const db=req.result;db.createObjectStore('journeys',{keyPath:'id'});for(const name of ['nodes','edges','jobs','topics']){const store=db.createObjectStore(name,{keyPath:'id'});store.createIndex('byJourney','journeyId');if(name==='nodes')store.createIndex('byJourneyUrl',['journeyId','url'],{unique:true});if(name==='edges')store.createIndex('byJourneyPair',['journeyId','from','to','type'],{unique:true});if(name==='jobs')store.createIndex('byStatus','status');}};const legacy=await request(req);const tx=legacy.transaction('journeys','readwrite');tx.objectStore('journeys').put({id,name:'QA Evidence',createdAt:Date.now()});await txDone(tx);legacy.close();}
 else probe.close();
 const db=await import('../extension/lib/db.js');if(!await db.get('journeys',id))await db.put('journeys',{id,name:'QA Evidence',createdAt:Date.now()});assert((await db.get('journeys',id)).name==='QA Evidence','Existing journey must survive');await db.getAll('evidenceBoards');await db.getAll('evidenceCaptures');
});
const db=await import('../extension/lib/db.js');const workspace=await import('../extension/evidence/workspace.js');const {collectSelection}=await import('../extension/evidence/selection.js');
for(const store of ['nodes','edges','jobs','topics','evidenceBoards','evidenceCaptures'])await db.deleteWhere(store,'byJourney',id);
await db.put('journeys',{id,name:'QA Evidence',createdAt:Date.now()});
let board;
await test('Arguments persist with monotonic revisions',async()=>{board=await workspace.createBoard(id,workspace.emptyBoard('Does the published rule support this?'));const content=structuredClone(board.content);content.nodes.push({id:'qa-claim',type:'claim',x:40,y:100,text:'Applications can be made throughout the year.'});content.steps=['qa-claim'];board=await workspace.saveBoard(board.id,0,content);assert(board.revision===1,'Revision increments');assert((await workspace.openWorkspace(new URLSearchParams({j:id,b:board.id}))).record.content.nodes.length===1,'Reopened board retains card');});
await test('A stale tab cannot overwrite another tab’s board',async()=>{let rejected=false;try{await workspace.saveBoard(board.id,0,workspace.emptyBoard('Stale overwrite'));}catch{rejected=true;}assert(rejected,'Stale save must reject');assert((await db.get('evidenceBoards',board.id)).content.title===board.content.title,'Latest content stays intact');});
const original={id:'qa-capture',journeyId:id,title:'Published application rules',url:'https://example.org/policy#eligibility',quote:'Applications are accepted throughout the year.',view:'original',capturedAt:Date.now(),anchor:{exact:'Applications are accepted throughout the year.',prefix:'Eligibility: ',suffix:' Forms are available below.'}};
await test('Deleting or revisiting a source page does not mutate authored evidence',async()=>{await db.put('nodes',{id:'qa-page',journeyId:id,url:'https://example.org/policy',title:'Rules',highlights:[]});await db.put('evidenceCaptures',{...original,pageId:'qa-page'});const card=workspace.evidenceCard({...original,pageId:'qa-page'},{x:430,y:100});board.content.nodes.push(card);board.content.links.push({id:'qa-link',from:card.id,to:'qa-claim',kind:'supports',label:'Year-round applications'});board=await workspace.saveBoard(board.id,board.revision,board.content);await db.remove('nodes','qa-page');assert((await db.get('evidenceBoards',board.id)).content.nodes[1].quote===original.quote,'Snapshot quote survives');assert((await workspace.inbox(id)).some(c=>c.id===original.id),'Capture survives');});
await test('Translated and legacy highlights stay unverified',async()=>{for(const view of ['translated','legacy-unverified']){const card=workspace.evidenceCard({...original,view},{x:0,y:0});assert(!card.quote,'No original-language text fragment may be fabricated');assert(card.displayedQuote===original.quote,'Captured text remains available');}await db.put('nodes',{id:'qa-legacy-page',journeyId:id,url:'https://example.org/legacy',title:'Existing highlight',highlights:[{text:'A previously saved passage.',at:Date.now()}]});assert((await workspace.inbox(id)).some(c=>c.legacy),'Existing highlight exposed in inbox');});
await test('Selection capture records exact words, prefix, suffix and translated status',async()=>{const fixture=document.querySelector('#fixture');fixture.innerHTML='<p id="source">Before. Applications are accepted throughout the year. After.</p>';const text=fixture.firstChild.firstChild,range=document.createRange();range.setStart(text,8);range.setEnd(text,text.textContent.indexOf(' After.'));window.getSelection().removeAllRanges();window.getSelection().addRange(range);const result=collectSelection();assert(result.quote==='Applications are accepted throughout the year.','Exact selection preserved');assert(result.anchor.prefix==='Before. ','Context prefix preserved');fixture.firstChild.classList.add('ah-showing-en');assert(collectSelection().view==='translated','Translated view distinguished');window.getSelection().removeAllRanges();assert(collectSelection().view==='translated','Screenshot-only translated view distinguished');fixture.replaceChildren();});
let mockedSource={...original};let activeCalls=0,moved=false,selectionUnavailable=false;
globalThis.chrome={storage:{local:{get:async()=>({settings:{blocklist:['blocked.example']}})}},scripting:{executeScript:async()=>{if(selectionUnavailable)throw new Error('restricted');return [{result:mockedSource}];}},tabs:{query:async()=>{activeCalls++;return [{id:moved&&activeCalls>1?22:11,url:'https://example.org/policy'}];},captureVisibleTab:async()=> 'data:image/png;base64,aGVsbG8='}};
const {captureEvidence}=await import('../extension/evidence/capture-background.js');const tab={id:11,windowId:1,url:'https://example.org/policy',title:'Rules'};
await test('Capture rejects incognito, blocked sources and changed screenshot tabs',async()=>{for(const [candidate,info,shot] of [[{...tab,incognito:true},{},false],[{...tab,url:'https://blocked.example/private'},{},false],[tab,{},true]]){activeCalls=0;moved=shot;let rejected=false;try{await captureEvidence(candidate,info,id,shot);}catch{rejected=true;}assert(rejected,'Unsafe or mismatched capture must reject');}moved=false;});
await test('Lost selections are not mislabeled as verified source wording',async()=>{mockedSource={...original,quote:''};const capture=await captureEvidence(tab,{selectionText:'Selected before the menu opened'},id);assert(capture.view==='legacy-unverified','Mismatch marked unverified');assert(!workspace.evidenceCard(capture,{x:0,y:0}).quote,'No misleading fragment');});
await test('Original capture retains full URL and text anchor',async()=>{mockedSource={...original};const capture=await captureEvidence(tab,{selectionText:original.quote},id);assert(capture.url.endsWith('#eligibility'),'Exact source URL retained separately from canonical page URL');assert(capture.anchor.prefix===original.anchor.prefix,'Text context retained');});
await test('Restricted selections remain usable as unverified evidence',async()=>{selectionUnavailable=true;const capture=await captureEvidence(tab,{selectionText:'A restricted-page quote'},id);assert(capture.quote==='A restricted-page quote','Context-menu quote retained');assert(capture.view==='legacy-unverified','Restriction recorded');selectionUnavailable=false;});
await db.put('evidenceCaptures',{...original,id:'qa-translated',quote:'An English rendering of a German rule.',view:'translated',note:'Translation captured from the page, not original source wording.'});
const link=document.querySelector('#open-board');link.href='../extension/evidence/index.html?'+new URLSearchParams({j:id,b:board.id,author:'1',inbox:'1'});link.textContent='Open seeded manual board';link.hidden=false;
document.querySelector('#status').textContent=failures?`${failures} check(s) failed`:'All 10 integration checks passed. No AI calls were made.';
document.documentElement.dataset.testResult=failures?'failed':'passed';
