const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
const safeURL=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
const domain=s=>{try{return new URL(s).hostname.replace(/^www\./,'')}catch{return 'Source'}};
const deepLink=n=>{const u=safeURL(n.url);if(!u)return '';if(n.pdf)return u.split('#')[0]+(n.page?'#page='+n.page:'');return u.split('#')[0]+(n.quote?'#:~:text='+encodeURIComponent(n.quote.trim()).replace(/-/g,'%2D'):'')};
const readerMode=!!document.getElementById('seed-board');
const workspace = readerMode ? null : await import('./workspace.js');
let session = null;
if (workspace) {
  try { session = await workspace.openWorkspace(new URLSearchParams(location.search)); }
  catch (error) {
    document.body.replaceChildren();
    const message = document.createElement('p'); message.textContent = error.message;
    const back = document.createElement('a'); back.href = '../journey/journey.html'; back.textContent = 'Return to workspaces';
    document.body.append(message, back);
    throw error;
  }
}

let board=readerMode?validateBoard(JSON.parse(document.getElementById('seed-board').textContent)):validateBoard(session.record.content), selected=null, author=false, zoom=.85, allRoutes=false, tab='map', walking=false, step=0;
const route=()=>board.kind==='trade'?'A':board.profit==='above'?'B':'C';
const active=n=>!board.sample||!n.route||n.route===route();
const visibleNodes=()=>board.nodes.filter(n=>allRoutes||active(n));
const get=id=>board.nodes.find(n=>n.id===id);
const typeLabel=t=>({gap:'OPEN QUESTION',note:'THOUGHT'})[t]||String(t).toUpperCase();const renderHooks=[];
const wording=n=>n.dynamic==='kind'?(board.kind==='trade'?'Self-employed with a trade licence':'Freelance work, no trade licence'):n.dynamic==='profit'?(board.profit==='above'?'Expected annual profit above €6,613.20':'Expected annual profit at or below €6,613.20'):n.text;
const pos=n=>({x:n.x,y:n.y+(allRoutes&&n.route?(['A','B','C'].indexOf(n.route))*1050:0)});
const sequence=()=>board.steps.map(get).filter(n=>n&&active(n));
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3200)}
function persist(){commitBoard();}
function figure(n){return n.image?`<div class="crop"><img src="${esc(n.image)}" alt="Screenshot evidence: ${esc(n.text)}">${(n.highlights||[]).map(h=>`<span class="highlight" style="left:${h.x*100}%;top:${h.y*100}%;width:${h.w*100}%;height:${h.h*100}%"></span>`).join('')}</div><div class="image-label">USER-SUPPLIED SCREENSHOT</div>`:''}
function card(n,inline=false){const p=pos(n);const title=wording(n),challenged=board.links.some(l=>l.to===n.id&&l.kind==='challenges');const hasSource=board.links.some(l=>l.to===n.id&&l.kind==='supports'&&get(l.from)?.type==='evidence');return `<article tabindex="0" role="button" aria-label="${author&&!readerMode?'Edit':'Inspect'} ${esc(n.type)}: ${esc(title)}" data-node="${esc(n.id)}" class="card ${n.type} ${author&&!readerMode?'is-editable':''} ${selected===n.id?'selected':''}" style="left:${p.x}px;top:${p.y}px">${author&&!readerMode?`<span class="drag-hint" title="Drag this card to move it. With the card focused, use arrow keys; Shift moves farther.">⠿ Drag to move</span><button class="edit-affordance card-edit" data-edit="${esc(n.id)}" aria-label="Edit ${esc(n.type)}: ${esc(title)}">✎ Edit</button><button class="card-inspect" data-inspect-card="${esc(n.id)}" aria-label="Inspect connections for ${esc(title)}">Connections</button>`:''}${n.type==='evidence'?`<div class="source-head"><span class="domain">${esc(domain(n.url))}</span><span class="pill ${n.tier==='Primary'?'primary':''}">${esc(n.tier||'Unreviewed')}</span></div>${figure(n)}<div class="source-body"><p class="source-title">${esc(title)}</p>${n.quote?`<p class="excerpt"><mark>${esc(n.quote)}</mark></p>`:''}${n.note?`<p class="translation">${esc(n.note)}</p>`:''}</div><div class="source-footer">${deepLink(n)?`<a href="${esc(deepLink(n))}" target="_blank" rel="noopener noreferrer">${n.pdf?'Open PDF ↗':n.quote?'Open at passage ↗':'Open source ↗'}</a>`:'<span>No source URL</span>'}<span>${esc(n.checked||'Not checked')}</span></div>`:`<p class="eyebrow">${esc(typeLabel(n.type))}${challenged?' · CHALLENGED':''}</p>${n.type==='fact'?`<p>${esc(title)}</p>`:`<h3>${esc(title)}</h3>`}${n.type==='claim'?`<div class="status">${challenged?'↯ Conflicting evidence':hasSource?'↳ Linked evidence':'○ No evidence attached'}</div>`:''}`}</article>`}
function render(){
 const untitled=board.title==='What am I trying to establish?';$('#board-title').textContent=untitled?'Untitled question':board.title;$('#board-title').classList.toggle('is-placeholder',untitled);$('.subtitle').textContent=board.subtitle||'';$('.subtitle').hidden=!board.subtitle;$('.case-heading .eyebrow').textContent=board.sample?'CASE 001 / HEALTH INSURANCE IN AUSTRIA':(session?session.journey.name.toUpperCase()+' / EVIDENCE BOARD':'SHARED EVIDENCE BOARD');
 const conclusion=board.nodes.find(n=>n.type==='conclusion'&&active(n));$('#verdict').textContent=conclusion?wording(conclusion):'';$('.verdict').hidden=!conclusion;$('#edit-heading').hidden=!author||readerMode;$('#edit-conclusion').hidden=!author||readerMode||!conclusion;$('#edit-conclusion').dataset.edit=conclusion?.id||'';for(const el of [$('#board-title'),$('.subtitle'),$('#verdict')]){el.classList.toggle('click-to-edit',author&&!readerMode);if(author&&!readerMode){el.tabIndex=0;el.title='Click to edit'}else{el.removeAttribute('tabindex');el.removeAttribute('title')}}
 $('.segmented').hidden=readerMode||tab==='outline';$('#mode-hint').textContent=tab==='outline'&&!readerMode?'Outline · type to edit':readerMode?'Read-only export':author?'Click to edit · drag to move':'Viewing · switch to Author to edit';
 $$('.field-inline').forEach(el=>el.hidden=!board.sample);$('#kind').value=board.kind||'trade';$('#profit').value=board.profit||'above';$('.check-label').hidden=!board.sample;
 $('#view').setAttribute('aria-pressed',!author);$('#author').setAttribute('aria-pressed',author);$('#authorbar').hidden=!author||walking||tab==='outline';$('#walk').textContent=walking?'■ End walkthrough':'▶ Walk through';
 $('#viewport').hidden=walking||tab!=='map';if($('#outline-view')){$('#outline-view').hidden=walking||tab!=='outline';$('#outline-tab').classList.toggle('active',tab==='outline');$('#outline-tab').hidden=readerMode}$('#source-list').hidden=walking||tab!=='sources';$('#walkthrough').hidden=!walking;$('.canvas-footer').hidden=walking||tab!=='map';$('.board-bar').hidden=walking;
 $('#map-tab').classList.toggle('active',tab==='map');$('#sources-tab').classList.toggle('active',tab==='sources');$('#source-count').textContent=board.nodes.filter(n=>n.type==='evidence').length;
 const nodes=visibleNodes();let width=Math.max(1480,...nodes.map(n=>n.x+360)),height=Math.max(850,...nodes.map(n=>pos(n).y+460));
 $('#canvas').style.width=width+'px';$('#canvas').style.height=height+'px';$('#canvas').style.transform=`scale(${zoom})`;$('#sizer').style.width=width*zoom+'px';$('#sizer').style.height=height*zoom+'px';$('#zoom-label').textContent=Math.round(zoom*100)+'%';
 $('#canvas').innerHTML=`<svg width="${width}" height="${height}" aria-hidden="true"></svg>${board.sample?`<div class="lane-label" style="left:30px;top:55px">01 / YOUR FACTS</div><div class="lane-label" style="left:340px;top:55px">02 / THE RULES & THEIR SOURCES</div><div class="lane-label" style="left:1100px;top:55px">03 / WHAT FOLLOWS</div>`:''}${nodes.map(n=>card(n)).join('')}${!nodes.length?'<div class="empty"><h2>Start with a question.<br>Build from the evidence.</h2><p>Add a fact, a claim, or a source using the authoring toolbar.</p>'+(readerMode?'':'<div class="empty-actions"><button class="dark" data-open-outline>✎ Start jotting</button><button data-guide="tour">▶ Take the guided tour</button><button data-guide="primer">How this works</button><button data-guide="author">Start authoring</button></div>')+'</div>':''}`;
 $('#source-list').innerHTML=`<p class="eyebrow">SOURCE LIBRARY · ALL ROUTES</p><div class="source-grid">${board.nodes.filter(n=>n.type==='evidence').map(n=>card(n,true)).join('')}</div>`;
 renderEdges();renderInspector();if(walking)renderWalk();
 for(const hook of renderHooks)hook();
}
function renderEdges(){const ids=new Set(visibleNodes().map(n=>n.id));const svg=$('#canvas svg');if(!svg)return;svg.innerHTML=`<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 1 1 L 9 5 L 1 9" fill="none" stroke="context-stroke"/></marker></defs>`+board.links.filter(l=>ids.has(l.from)&&ids.has(l.to)).map(l=>{const a=get(l.from),b=get(l.to),ap=pos(a),bp=pos(b),ae=$(`#canvas [data-node="${CSS.escape(a.id)}"]`),be=$(`#canvas [data-node="${CSS.escape(b.id)}"]`);if(!ae||!be)return '';let sx,sy,tx,ty,d;
 if(bp.x>ap.x+ae.offsetWidth-10){sx=ap.x+ae.offsetWidth;sy=ap.y+Math.min(120,ae.offsetHeight)/2;tx=bp.x-6;ty=bp.y+Math.min(120,be.offsetHeight)/2;d=`M${sx},${sy} C${sx+45},${sy} ${tx-45},${ty} ${tx},${ty}`;}else{sx=ap.x+ae.offsetWidth/2;tx=bp.x+be.offsetWidth/2;const down=bp.y>ap.y;sy=ap.y+(down?ae.offsetHeight:0);ty=bp.y+(down?-7:be.offsetHeight+7);d=`M${sx},${sy} C${sx},${(sy+ty)/2} ${tx},${(sy+ty)/2} ${tx},${ty}`;}
 const color=l.kind==='challenges'?'#ac402d':l.kind==='supports'?'#a29575':'#817969';return `<path d="${d}" fill="none" stroke="${color}" stroke-width="1.5" ${l.kind!=='reasoning'?'stroke-dasharray="'+(l.kind==='supports'?'2 5':'6 4')+'"':''} marker-end="url(#arrow)"/>${l.label?`<text class="edge-label" text-anchor="middle" x="${(sx+tx)/2}" y="${(sy+ty)/2-10}">${esc(l.label)}</text>`:''}`}).join('');
 // Labels live in their own layer above the cards so a card never hides them.
 let top=$('#canvas svg.edge-labels');if(!top){top=document.createElementNS('http://www.w3.org/2000/svg','svg');top.setAttribute('class','edge-labels');top.setAttribute('aria-hidden','true');$('#canvas').append(top)}
 top.setAttribute('width',svg.getAttribute('width'));top.setAttribute('height',svg.getAttribute('height'));top.replaceChildren(...svg.querySelectorAll('text.edge-label'));}
function renderInspector(){const n=get(selected);if(!n){const activeNodes=board.nodes.filter(active),steps=sequence();const counts=[[activeNodes.filter(n=>n.type==='claim').length,'claims'],[activeNodes.filter(n=>n.type==='evidence').length,'sources'],[board.links.filter(l=>l.kind==='challenges'&&active(get(l.to)||{})).length,'challenges'],[activeNodes.filter(n=>n.type==='gap').length,'open questions']];$('#inspector').innerHTML=`<h2 class="panel-label">Walkthrough</h2><div class="reading-list">${steps.map((n,i)=>`<button data-select="${n.id}"><span class="num">${String(i+1).padStart(2,'0')}</span><span>${esc(wording(n))}</span></button>`).join('')}</div>${!steps.length?'<p class="ui-hint">No steps yet. In Author mode, select a card and add it to the walkthrough.</p>':''}<p class="board-summary">${counts.filter(([count])=>count).map(([count,label])=>`<span>${count} ${count===1?label.replace(/s$/,''):label}</span>`).join('')}</p><details class="reading-help"><summary>Reading this board</summary><p>Select a step or card to inspect its evidence and connections. Use Walk through to read in order.</p><p>${readerMode?'Shared board · read only.':'Evidence snapshots stay in this workspace. Save a board file for a portable backup.'}</p></details>${board.sample?'<p class="ui-hint">Example case · assumptions and open questions remain.</p>':''}`;return}
 const relations=board.links.filter(l=>l.to===n.id||l.from===n.id);$('#inspector').innerHTML=`<div class="detail-heading"><span class="eyebrow">${esc(typeLabel(n.type))}</span><button data-deselect aria-label="Close inspector">✕</button></div><p class="detail-copy">${esc(wording(n))}</p>${!readerMode?`<button class="edit-affordance" data-edit="${n.id}">✎ Edit ${n.type==='evidence'?'evidence & notes':'text & notes'}</button>`:'<span class="content-access">Read only</span>'}${n.type==='evidence'?`${figure(n)}${n.image?`<button data-inspect-image="${n.id}">Inspect screenshot ⤢</button>`:''}${n.quote?`<p class="excerpt"><mark>${esc(n.quote)}</mark></p>`:''}${deepLink(n)?`<a class="full-link" href="${esc(deepLink(n))}" target="_blank" rel="noopener noreferrer">${n.pdf?'Open PDF':n.quote?'Open source at passage':'Open source'} ↗</a><button data-copy-link="${n.id}">Copy source link</button>`:''}<dl class="detail-meta"><dt>Publisher</dt><dd>${esc(domain(n.url))}</dd><dt>Authority</dt><dd>${esc(n.tier||'Unreviewed')} · author-assigned</dd><dt>Checked</dt><dd>${esc(n.checked||'Not recorded')}</dd><dt>Captured <span class="fixed-label">recorded</span></dt><dd>${n.capturedAt?esc(new Date(n.capturedAt).toLocaleString()):'Not recorded'}</dd><dt>Page view <span class="fixed-label">recorded</span></dt><dd>${esc(n.provenance?.view||'Manually supplied')}</dd><dt>Capture</dt><dd>${n.image?'Uploaded screenshot':'Text excerpt · not a screenshot'}</dd></dl><details class="reading-help"><summary>About passage links</summary><p>Passage links depend on browser support and unchanged source text. PDFs use the page number when provided.</p></details>`:''}${n.note?`<div class="authored-note"><span class="eyebrow">Note</span><p>${esc(n.note)}</p></div>`:''}<p class="eyebrow" style="margin-top:25px">${relations.length?'CONNECTIONS':'NO CONNECTIONS YET'}</p>${relations.map(l=>{const incoming=l.to===n.id,other=get(incoming?l.from:l.to);return other?`<div class="detail-box"><small>${incoming?'←':'→'} ${esc(l.kind)}${l.label?' · '+esc(l.label):''}</small><button data-select="${other.id}">${esc(wording(other))}</button>${author?`<button data-edit-link="${l.id}" style="font-size:12px;margin-top:8px">Edit connection</button><button class="danger" data-remove-link="${l.id}" style="font-size:12px;margin-top:8px">Remove connection</button>`:''}</div>`:''}).join('')}${author?`<div class="detail-actions"><button data-connect="${n.id}">＋ Connect</button><button data-step="${n.id}">${board.steps.includes(n.id)?'Remove from':'Add to'} walkthrough</button><button data-delete="${n.id}" class="danger">Delete card</button></div>`:''}`;
}
function activateCard(id,center=false){select(id,center);if(author&&!readerMode)openCard(get(id).type,id)}
function select(id,center=false){selected=id;if(center&&get(id)){const n=get(id);if(board.sample&&n.route&&n.route!==route()){allRoutes=true;$('#all-routes').checked=true;}render();const p=pos(n);$('#viewport').scrollTo({left:Math.max(0,(p.x-70)*zoom),top:Math.max(0,(p.y-55)*zoom),behavior:'smooth'});}else render();}
function renderWalk(){const seq=sequence();step=Math.max(0,Math.min(step,seq.length-1));const n=seq[step];if(!n){$('#walkthrough').innerHTML='<div class="empty"><h2>No walkthrough steps yet.</h2><p>In Author mode, select cards and add them to the walkthrough.</p></div>';return}const ev=board.links.filter(l=>l.to===n.id&&['supports','challenges'].includes(l.kind)).map(l=>({n:get(l.from),kind:l.kind})).filter(x=>x.n);$('#walkthrough').innerHTML=`<div class="walk-shell"><p class="walk-count">STEP ${String(step+1).padStart(2,'0')} / ${String(seq.length).padStart(2,'0')} · ${esc(n.type.toUpperCase())}</p><h2 class="walk-title">${esc(wording(n))}</h2>${author&&!readerMode?`<button class="edit-affordance" data-edit="${n.id}">✎ Edit this step</button>`:''}${n.note?`<p class="walk-note">${esc(n.note)}</p>`:''}<div class="walk-evidence">${n.type==='evidence'?card(n,true):ev.map(e=>`<p class="eyebrow">${esc(e.kind.toUpperCase())}</p>${card(e.n,true)}`).join('')||`<p class="ui-hint">${n.type==='fact'?'Author-stated fact':n.type==='gap'?'Open question':'No supporting sources linked'}</p>`}</div><div class="walk-controls"><button id="prev-step" ${step===0?'disabled':''}>← Back</button><div class="progress">${seq.map((_,i)=>`<button data-walk-step="${i}" class="${i<=step?'done':''}" aria-label="Go to step ${i+1}"></button>`).join('')}</div><button id="next-step" class="dark">${step===seq.length-1?'Finish':'Next →'}</button></div></div>`;$('#inspector').innerHTML=`<h2 class="panel-label">Walkthrough</h2><div class="reading-list">${seq.map((s,i)=>`<button data-walk-step="${i}" ${i===step?'aria-current="step" style="color:var(--green);font-weight:600"':''}><span class="num">${String(i+1).padStart(2,'0')}</span>${esc(wording(s))}</button>`).join('')}</div>`}
$('#kind').onchange=e=>{board.kind=e.target.value;selected=null;persist();render()};$('#profit').onchange=e=>{board.profit=e.target.value;selected=null;persist();render()};$('#all-routes').onchange=e=>{allRoutes=e.target.checked;render()};$('#view').onclick=()=>{author=false;render()};$('#author').onclick=()=>{author=true;render()};$('#map-tab').onclick=()=>{tab='map';render()};if($('#outline-tab'))$('#outline-tab').onclick=()=>{tab='outline';render()};$('#sources-tab').onclick=()=>{tab='sources';render()};$('#zoom-in').onclick=()=>{zoom=Math.min(1.5,zoom+.1);render()};$('#zoom-out').onclick=()=>{zoom=Math.max(.35,zoom-.1);render()};$('#fit').onclick=()=>{zoom=Math.max(.35,Math.min(1,($('#viewport').clientWidth-35)/Math.max(1480,...visibleNodes().map(n=>n.x+350))));render();$('#viewport').scrollTo(0,0)};$('#walk').onclick=()=>{walking=!walking;step=0;render()};
document.addEventListener('click',e=>{const el=e.target.closest('[data-select],[data-deselect],[data-walk-step],#prev-step,#next-step,[data-node]');if(!el||e.target.closest('a,[data-edit],[data-inspect-card],#edit-heading'))return;if(el.hasAttribute('data-select'))activateCard(el.dataset.select,true);else if(el.hasAttribute('data-deselect')){selected=null;render()}else if(el.hasAttribute('data-walk-step')){step=Number(el.dataset.walkStep);renderWalk()}else if(el.id==='prev-step'){step--;renderWalk()}else if(el.id==='next-step'){if(step===sequence().length-1){walking=false;render()}else{step++;renderWalk()}}else if(el.dataset.node&&!dragMoved)activateCard(el.dataset.node);});
document.addEventListener('keydown',e=>{if(e.target.matches('[data-node]')&&['Enter',' '].includes(e.key)){e.preventDefault();activateCard(e.target.dataset.node)}if(walking&&!e.target.matches('input,textarea,select,[contenteditable]')&&!$('dialog[open]')){if(e.key==='ArrowRight')$('#next-step')?.click();if(e.key==='ArrowLeft')$('#prev-step')?.click();if(e.key==='Escape'){walking=false;render()}}});
let dragMoved=false;$('#viewport').addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('a,button'))return;const el=e.target.closest('[data-node]'),n=el&&get(el.dataset.node);if(n&&!author)return;const sx=e.clientX,sy=e.clientY,ox=n?.x,oy=n?.y,sl=$('#viewport').scrollLeft,st=$('#viewport').scrollTop;dragMoved=false;const move=ev=>{const dx=ev.clientX-sx,dy=ev.clientY-sy;if(Math.hypot(dx,dy)<4&&!dragMoved)return;dragMoved=true;if(n){n.x=Math.max(0,ox+dx/zoom);n.y=Math.max(0,oy+dy/zoom);const p=pos(n);el.style.left=p.x+'px';el.style.top=p.y+'px';renderEdges()}else{$('#viewport').scrollLeft=sl-dx;$('#viewport').scrollTop=st-dy}};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);if(n&&dragMoved){delete n.auto;persist();setTimeout(render,0)}setTimeout(()=>dragMoved=false,50)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});});
window.addEventListener('resize',()=>renderEdges());document.fonts.ready.then(renderEdges);document.addEventListener('load',e=>{if(e.target.tagName==='IMG')renderEdges()},true);
let history=[],future=[],lastSnapshot=JSON.stringify(board),unsaved=false;
let saveQueue=Promise.resolve(), saveBlocked=false, saveSerial=0;
function commitBoard(record=true) {
  if(readerMode)return;
  const content=structuredClone(board), current=JSON.stringify(content);
  if(record&&current!==lastSnapshot){history.push(lastSnapshot);if(history.length>25)history.shift();future=[]}
  lastSnapshot=current;unsaved=true;updateHistory();
  const serial=++saveSerial;
  $('#save-status').textContent='Saving to workspace…';
  saveQueue=saveQueue.then(async()=>{
    if(saveBlocked)throw new Error('Saving paused after a conflict. Save a board file before reloading.');
    session.record=await workspace.saveBoard(session.record.id,session.record.revision,content);
    if(serial===saveSerial){unsaved=false;$('#save-status').textContent='Saved in '+session.journey.name;}
    const option=$('#board-picker')?.selectedOptions[0];if(option)option.textContent=content.title==='What am I trying to establish?'?'Untitled question':content.title;
  }).catch(error=>{saveBlocked=true;$('#save-status').textContent='Not saved · export your board';notify(error.message);});
}
function updateHistory(){if($('#undo')){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length}}
function undo(redo=false){const src=redo?future:history,dst=redo?history:future;if(!src.length)return;dst.push(JSON.stringify(board));board=JSON.parse(src.pop());lastSnapshot=JSON.stringify(board);selected=null;walking=false;commitBoard(false);render();notify(redo?'Change restored':'Change undone')}
function download(name,content,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
const filename=()=>board.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,65)||'evidence-board';
$('.top-actions').insertAdjacentHTML('afterbegin','<button id="new-board">＋ New board</button>');
$('#authorbar').insertAdjacentHTML('afterbegin','<button id="add-fact">＋ Fact</button>');
$('#authorbar').insertAdjacentHTML('beforeend','<button id="layout-spacing">↔ Spacing</button><button id="order-steps">Order steps</button><button id="undo" aria-label="Undo change">↶</button><button id="redo" aria-label="Redo change">↷</button>');
$('#new-board').onclick=async()=>{
  await saveQueue;if(saveBlocked){notify('Save your board file and reload before switching boards.');return;}
  const record=await workspace.createBoard(session.journey.id);
  location.href='?'+new URLSearchParams({j:session.journey.id,b:record.id,author:'1',new:'1'});
};
$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);
$('#export').onclick=()=>{download(filename()+'.evidence.json',JSON.stringify(board,null,2));notify('Board file saved, including screenshot crops and highlights')};
$('#import').onclick=()=>$('#import-file').click();
function validateBoard(input){
 const bad=msg=>{throw new Error(msg)};
 if(!input||input.version!==1||typeof input.title!=='string'||!Array.isArray(input.nodes)||!Array.isArray(input.links)||!Array.isArray(input.steps))bad('This is not a supported Evidence Walkthrough board.');
 if(input.nodes.length>500||input.links.length>2000||input.steps.length>500)bad('This board exceeds the 500-card limit.');
 const str=(s,max=30000)=>typeof s==='string'&&s.length<=max;const ids=new Set();
 const nodes=input.nodes.map(n=>{if(!n||!str(n.id,100)||ids.has(n.id)||!['note','fact','claim','conclusion','gap','evidence'].includes(n.type)||!str(n.text)||![n.x,n.y].every(v=>Number.isFinite(v)&&v>=0&&v<=30000))bad('A card contains invalid data.');ids.add(n.id);
 const clean={id:n.id,type:n.type,text:n.text,x:n.x,y:n.y};for(const k of ['note','quote','url','tier','checked','route','dynamic','sourceCaptureId','sourcePageId','displayedQuote'])if(n[k]!==undefined){if(!str(n[k]))bad('Invalid card text.');clean[k]=n[k]}
 if(n.capturedAt!==undefined){if(!Number.isFinite(n.capturedAt))bad('Invalid capture date.');clean.capturedAt=n.capturedAt;}
 if(n.provenance){const v=n.provenance;if(!v||!str(v.view,100)||!str(v.frameUrl||'',10000))bad('Invalid provenance.');clean.provenance={view:v.view,frameUrl:v.frameUrl||''};if(v.anchor){for(const k of ['exact','prefix','suffix'])if(!str(v.anchor[k]||''))bad('Invalid source anchor.');clean.provenance.anchor={exact:v.anchor.exact||'',prefix:v.anchor.prefix||'',suffix:v.anchor.suffix||''};}}
 if(clean.url&&!safeURL(clean.url))bad('Source links must start with https:// or http://.');
 for(const k of ['image','originalImage'])if(n[k]){if(!str(n[k],22000000)||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(n[k]))bad('Unsupported screenshot format.');clean[k]=n[k]}
 if(n.pdf)clean.pdf=true;if(n.auto===true)clean.auto=true;if(n.ord!==undefined){if(!Number.isFinite(n.ord))bad('Invalid outline order.');clean.ord=n.ord}if(n.page!==undefined){if(!Number.isInteger(Number(n.page))||n.page<1||n.page>100000)bad('Invalid PDF page.');clean.page=Number(n.page)}
 if(n.highlights!==undefined){if(!Array.isArray(n.highlights)||n.highlights.length>200)bad('Invalid highlights.');clean.highlights=n.highlights.map(h=>{if(!h||!['x','y','w','h'].every(k=>Number.isFinite(h[k])&&h[k]>=0&&h[k]<=1)||h.x+h.w>1.001||h.y+h.h>1.001)bad('Invalid highlight coordinates.');return {x:h.x,y:h.y,w:h.w,h:h.h}})}return clean;});
 const linkIds=new Set();const links=input.links.map(l=>{if(!l||!str(l.id,100)||linkIds.has(l.id)||!ids.has(l.from)||!ids.has(l.to)||l.from===l.to||!['supports','challenges','reasoning','questions'].includes(l.kind)||!str(l.label||'',500))bad('A connection contains invalid data.');linkIds.add(l.id);return {id:l.id,from:l.from,to:l.to,kind:fitKind(nodes.find(n=>n.id===l.from).type,l.kind),label:l.label||''}});
 if(!input.steps.every(id=>ids.has(id))||new Set(input.steps).size!==input.steps.length)bad('Invalid walkthrough sequence.');
 return {version:1,title:input.title.slice(0,500),subtitle:str(input.subtitle)?input.subtitle:'',sample:input.sample===true,kind:input.kind==='trade'?'trade':'freelance',profit:input.profit==='above'?'above':'below',nodes,links,steps:[...input.steps]};
}
// A connection's kind follows from the card it starts at: a quote is a source
// for (or against) something, a question raises a question, anything else is
// a reason for (or against) it. Declared as functions so loading can use them.
function allowedKinds(t){return t==='evidence'?['supports','challenges']:t==='gap'?['questions']:['reasoning','challenges']}
function fitKind(t,k){return allowedKinds(t).includes(k)?k:t==='gap'?'questions':['challenges','questions'].includes(k)?'challenges':allowedKinds(t)[0]}
$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>40*1024*1024)throw new Error('Please choose a board file smaller than 40 MB.');const next=validateBoard(JSON.parse(await file.text()));await saveQueue;if(saveBlocked)throw new Error('Save the current board file and reload first.');const imported=await workspace.createBoard(session.journey.id,next);session.record=imported;session.boards.push(imported);window.history.replaceState(null,'','?'+new URLSearchParams({j:session.journey.id,b:imported.id}));history=[];future=[];board=next;lastSnapshot=JSON.stringify(board);refreshPicker();selected=null;walking=false;tab='map';allRoutes=false;$('#all-routes').checked=false;persist();render();notify('Imported as a new board in this workspace.')}catch(err){notify(err.message||'Could not read this board file.')}finally{e.target.value=''}};
let editorMode='',editingId=null,capture={image:'',originalImage:'',highlights:[]},captureMode='highlight',cropRect=null,captureBusy=false;
const input=(id,label,value='',type='text',required=false)=>`<label class="form-label" for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(value)}" ${required?'required':''}>`;
const area=(id,label,value='',required=false)=>`<label class="form-label" for="${id}">${label}</label><textarea id="${id}" rows="3" ${required?'required':''}>${esc(value)}</textarea>`;
const options=(values,current)=>values.map(([v,l])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(l)}</option>`).join('');
function showEditor(title,html,mode){editorMode=mode;$('#editor-title').textContent=title;$('#editor-fields').innerHTML=html;$('#form-error').textContent='';$('#editor-form button[type=submit]').textContent=mode==='order'?'Save order':'Save to board';$('#editor').showModal()}
function openSpacing(){
 let dialog=$('#spacing-dialog');
 if(!dialog){dialog=document.createElement('dialog');dialog.id='spacing-dialog';document.body.append(dialog)}
 const n=get(selected);
 dialog.innerHTML=`<div class="dialog-heading"><h2>Arrange cards</h2><button data-close aria-label="Close spacing">✕</button></div><p class="form-help">Drag any card in Author mode. For precise movement, focus a card and use arrow keys (10 px), or Shift + arrows (50 px).</p>
 ${n?`<fieldset><legend>Selected card</legend><p>${esc(wording(n))}</p><div class="form-row"><div>${input('position-x','Left (px)',Math.round(n.x),'number')}</div><div>${input('position-y','Top (px)',Math.round(n.y),'number')}</div></div><button id="apply-position">Move card</button></fieldset>`:''}
 <fieldset><legend>Space visible columns</legend><p class="form-help">Cards with left edges within 80 px are treated as a column. Keeps column order and each column’s top-to-bottom order. Hidden routes stay unchanged.</p><div class="form-row"><div>${input('column-gap','Between columns (px)',140,'number')}</div><div>${input('row-gap','Between cards (px)',80,'number')}</div></div><p class="form-help">Measured from card edges, including tall evidence cards. Apply once; Undo restores the previous layout.</p><button id="apply-spacing">Apply spacing</button></fieldset><p id="spacing-error" class="error" role="alert"></p>`;
 dialog.querySelectorAll('input').forEach(el=>{el.min=0;el.max=10000;el.step=10});
 const value=id=>{const el=$(id),v=Number(el.value);if(!el.value.trim()||!Number.isFinite(v)||v<0||v>10000)throw new Error('Use a distance between 0 and 10,000 px.');return v};
 $('#apply-position')?.addEventListener('click',()=>{try{const x=value('#position-x'),y=value('#position-y');Object.assign(n,{x,y});delete n.auto;persist();render();dialog.close();select(n.id,true)}catch(e){$('#spacing-error').textContent=e.message}});
 $('#apply-spacing').onclick=()=>{try{
 const gapX=value('#column-gap'),gapY=value('#row-gap');
 const nodes=visibleNodes().map(n=>{const el=$(`#canvas [data-node="${CSS.escape(n.id)}"]`);return {n,w:el?.offsetWidth||300,h:el?.offsetHeight||200}});
 if(!nodes.length)throw new Error('Add cards before adjusting spacing.');
 const positions=spacedPositions(nodes,gapX,gapY);
 positions.forEach(({n,x,y})=>{Object.assign(n,{x,y});delete n.auto});persist();render();dialog.close();notify('Spacing applied. Undo restores the previous layout.');
 }catch(e){$('#spacing-error').textContent=e.message}};
 dialog.showModal();
}
function spacedPositions(nodes,gapX,gapY){
 const columns=[];
 for(const item of [...nodes].sort((a,b)=>a.n.x-b.n.x||a.n.y-b.n.y)){
  let column=columns.at(-1);
  if(!column||item.n.x-column.left>80){column={left:item.n.x,items:[]};columns.push(column)}
  column.items.push(item);
 }
 let x=Math.min(...nodes.map(({n})=>n.x));const result=[];
 for(const column of columns){
  let y=Math.min(...column.items.map(({n})=>n.y));
  for(const {n,h} of column.items.sort((a,b)=>a.n.y-b.n.y)){
   result.push({n,x,y});y+=h+gapY;
  }
  x+=Math.max(...column.items.map(item=>item.w))+gapX;
 }
 return result;
}
$('#layout-spacing').onclick=openSpacing;
function openTitle(){showEditor('Your question',input('title-text','Question or board title',board.title,'text',true)+area('subtitle-text','Context or scope',board.subtitle),'title')}
$('#edit-title').onclick=openTitle;$('#edit-heading').onclick=openTitle;
for(const el of [$('#board-title'),$('.subtitle'),$('#verdict')]){
 const edit=()=>{if(!author||readerMode)return;if(el.id==='verdict'){const n=board.nodes.find(n=>n.type==='conclusion'&&active(n));if(n)activateCard(n.id)}else openTitle()};
 el.onclick=edit;el.onkeydown=e=>{if(['Enter',' '].includes(e.key)&&author&&!readerMode){e.preventDefault();edit()}};
}
function openCard(type='claim',id=null){const n=id?get(id):null;editingId=id;capture={image:n?.image||'',originalImage:n?.originalImage||n?.image||'',highlights:structuredClone(n?.highlights||[])};cropRect=null;captureMode='highlight';
 const shared=area('card-note',type==='evidence'?'Translation, context or annotation':'Notes, assumptions or reasoning',n?.note||'')+(board.sample?`<label class="form-label" for="card-route">Case route</label><select id="card-route">${options([['','All routes'],['A','Trade licence'],['B','Freelance · above threshold'],['C','Freelance · at or below threshold']],n?.route||(!n?route():''))}</select>`:'');
 if(type==='evidence'){showEditor(id?'Edit evidence':'Attach evidence',(n?.sourceCaptureId?'<p class="form-help">Editing this board’s copy. The original capture in your inbox stays unchanged.</p>':'')+input('card-text','Source title',n?.text||'','text',true)+input('card-url','Source URL',n?.url||'','url')+(n?.displayedQuote&&!n.quote?`<div class="notice"><b>Captured text · original not verified</b><p>${esc(n.displayedQuote)}</p><small>You can keep this as captured evidence. Paste verified original wording below only after checking the source.</small></div>`:'')+area('card-quote','Exact passage (creates a highlighted deep link)',n?.quote||'')+'<p class="form-help">Paste the exact original wording. The source URL is kept with the screenshot; no page is fetched automatically.</p>'+shared+`<div class="form-row"><div><label class="form-label" for="card-tier">Source authority · your assessment</label><select id="card-tier">${options([['Unreviewed','Unreviewed'],['Primary','Primary'],['Secondary','Secondary']],n?.tier||'Unreviewed')}</select></div><div>${input('card-checked','Date checked',n?.checked||'','date')}</div></div><div class="form-row"><div><label class="form-label check-label"><input type="checkbox" id="card-pdf" ${n?.pdf?'checked':''}> This source is a PDF</label></div><div>${input('card-page','PDF page (optional)',n?.page||'','number')}</div></div><label class="form-label" for="capture-file">Screenshot · upload or paste an image</label><input type="file" id="capture-file" accept="image/png,image/jpeg,image/webp"><p class="form-help">PNG, JPEG or WebP, up to 12 MB. Drag over the image to highlight or crop. Images stay in your board.</p><div id="capture-tools"></div>`,'card');$('#capture-file').onchange=async e=>{if(e.target.files[0])await readImage(e.target.files[0]);e.target.value=''};renderCapture();}
 else showEditor(id?'Edit card':'Add '+(type==='gap'?'open question':type),`<label class="form-label" for="card-type">Card type</label><select id="card-type">${options([['note','Thought (not sorted yet)'],['fact','Fact'],['claim','Claim'],['conclusion','Conclusion'],['gap','Open question']],n?.type||type)}</select>`+area('card-text','Text',n?wording(n):'',true)+shared,'card');
}
$('#add-claim').onclick=()=>openCard('claim');$('#add-fact').onclick=()=>openCard('fact');$('#add-gap').onclick=()=>openCard('gap');$('#add-source').onclick=()=>openCard('evidence');
function openConnection(id,linkId=null){const l=linkId&&board.links.find(l=>l.id===linkId),n=get(id);editingId=linkId;const opts=board.nodes.map(n=>[n.id,n.type+': '+wording(n).slice(0,85)]);showEditor(l?'Edit connection':'Connect two cards',`<label class="form-label" for="link-from">From</label><select id="link-from">${options(opts,l?.from||id)}</select><label class="form-label" for="link-kind">Relationship</label><select id="link-kind">${options([['reasoning','is a reason for'],['supports','is a source for'],['challenges','pushes back on'],['questions','raises a question about']],l?.kind||(n?.type==='evidence'?'supports':'reasoning'))}</select><label class="form-label" for="link-to">To</label><select id="link-to">${options(opts,l?.to||board.nodes.find(n=>n.id!==id)?.id)}</select>`+input('link-label','Why are these connected?',l?.label||'')+'<p class="form-help">Connections are authored by you. “Supports” does not verify a claim. Contradictions stay visible until you edit or remove the connection.</p>','connection');$('#link-from').onchange=syncLinkKinds;syncLinkKinds()}
function syncLinkKinds(){const t=get($('#link-from').value)?.type,sel=$('#link-kind'),allowed=allowedKinds(t);for(const o of sel.options)o.hidden=o.disabled=!allowed.includes(o.value);if(!allowed.includes(sel.value))sel.value=allowed[0]}
let draftSteps=[];
function openOrder(){draftSteps=[...board.steps];showEditor('Arrange the walkthrough','<p class="form-help">These steps define the reading order. Sample-case routes only show their applicable steps.</p><div id="step-order"></div>','order');renderOrder()}
function renderOrder(){$('#step-order').innerHTML=draftSteps.map((id,i)=>`<div class="order-row"><span>${String(i+1).padStart(2,'0')}</span><p>${esc(wording(get(id)))}</p><button type="button" data-order-up="${i}" aria-label="Move step ${i+1} up" ${i===0?'disabled':''}>↑</button><button type="button" data-order-down="${i}" aria-label="Move step ${i+1} down" ${i===draftSteps.length-1?'disabled':''}>↓</button><button type="button" data-order-remove="${i}" aria-label="Remove step ${i+1}">✕</button></div>`).join('')+`<label class="form-label" for="step-add">Add another card</label><div class="form-row"><select id="step-add">${options(board.nodes.filter(n=>!draftSteps.includes(n.id)).map(n=>[n.id,wording(n).slice(0,80)]),'')}</select><button type="button" id="step-add-button" ${draftSteps.length===board.nodes.length?'disabled':''}>Add step</button></div>`}
$('#order-steps').onclick=openOrder;
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;const d=el.dataset;if('close'in d)el.closest('dialog').close();else if(d.inspectCard){select(d.inspectCard)}else if(d.edit&&!readerMode){author=true;render();openCard(get(d.edit).type,d.edit);}else if(d.connect)openConnection(d.connect);else if(d.editLink)openConnection(null,d.editLink);else if(d.delete){board.nodes=board.nodes.filter(n=>n.id!==d.delete);board.links=board.links.filter(l=>l.from!==d.delete&&l.to!==d.delete);board.steps=board.steps.filter(id=>id!==d.delete);selected=null;persist();render();notify('Card removed. Use Undo to restore it.')}else if(d.removeLink){board.links=board.links.filter(l=>l.id!==d.removeLink);persist();render()}else if(d.step){board.steps=board.steps.includes(d.step)?board.steps.filter(id=>id!==d.step):[...board.steps,d.step];persist();render()}else if(d.inspectImage)inspectImage(d.inspectImage);else if(d.copyLink)copyText(deepLink(get(d.copyLink)));else if('orderUp'in d||'orderDown'in d){const i=Number(d.orderUp??d.orderDown),j=i+('orderUp'in d?-1:1);[draftSteps[i],draftSteps[j]]=[draftSteps[j],draftSteps[i]];renderOrder()}else if('orderRemove'in d){draftSteps.splice(Number(d.orderRemove),1);renderOrder()}else if(el.id==='step-add-button'){const id=$('#step-add').value;if(id&&!draftSteps.includes(id)){draftSteps.push(id);renderOrder()}}});
$('#editor-form').onsubmit=e=>{e.preventDefault();try{if(editorMode==='title'){const title=$('#title-text').value.trim();if(!title)throw new Error('Give this board a question or title.');board.title=title;board.subtitle=$('#subtitle-text').value.trim()}
 else if(editorMode==='order')board.steps=[...draftSteps];
 else if(editorMode==='connection'){const from=$('#link-from').value,to=$('#link-to').value,kind=$('#link-kind').value;if(!get(from)||!get(to)||from===to)throw new Error('Choose two different cards.');if(!allowedKinds(get(from).type).includes(kind))throw new Error('That kind of connection doesn’t fit this card. Change the card’s type or pick another connection.');const link={id:editingId||uid(),from,to,kind,label:$('#link-label').value.trim()};if(board.links.some(l=>l.id!==editingId&&l.from===from&&l.to===to&&l.kind===kind))throw new Error('That connection already exists.');if(editingId)board.links=board.links.map(l=>l.id===editingId?link:l);else board.links.push(link)}
 else{if(captureBusy)throw new Error('Wait for the image to finish loading.');const prior=editingId&&get(editingId),type=$('#card-type')?.value||'evidence',text=$('#card-text').value.trim();if(!text)throw new Error('Add text or a source title.');const vp=$('#viewport'),place=freePosition();const n={...(prior||{}),id:editingId||uid(),type,text,note:$('#card-note').value.trim(),x:prior?.x??place.x,y:prior?.y??place.y};delete n.dynamic;n.route=$('#card-route')?.value||'';
 if(type==='evidence'){const url=$('#card-url').value.trim();if(url&&!safeURL(url))throw new Error('Use an http:// or https:// source URL.');Object.assign(n,{url,quote:$('#card-quote').value.trim(),tier:$('#card-tier').value,checked:$('#card-checked').value,pdf:$('#card-pdf').checked,...capture});delete n.page;const page=$('#card-page').value;if(page){if(!Number.isInteger(Number(page))||Number(page)<1)throw new Error('PDF page must be a positive whole number.');n.page=Number(page)}if(!n.quote&&!n.image&&!n.displayedQuote)throw new Error('Paste a passage or attach a screenshot.');}
 if(prior)board.nodes=board.nodes.map(x=>x.id===editingId?n:x);else {board.nodes.push(n);if(!['evidence','note'].includes(type))board.steps.push(n.id)}if(prior&&prior.type==='note'&&!['evidence','note'].includes(type)&&!board.steps.includes(n.id))board.steps.push(n.id);board.links.forEach(l=>{if(l.from===n.id)l.kind=fitKind(n.type,l.kind)});selected=n.id;
 }persist();$('#editor').close();render();notify('Saved to board');}catch(err){$('#form-error').textContent=err.message}};
async function readImage(file){captureBusy=true;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Choose a PNG, JPEG or WebP image.');if(file.size>12*1024*1024)throw new Error('Choose an image smaller than 12 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const img=await loadImage(data);if(img.width*img.height>45000000)throw new Error('This image is too large. Use a smaller screenshot.');const ratio=Math.min(1,3000/img.width,9000/img.height);const c=document.createElement('canvas');c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const normalized=c.toDataURL('image/png');capture={image:normalized,originalImage:normalized,highlights:[]};cropRect=null;renderCapture();}catch(err){$('#form-error').textContent=err.message||'Unable to read this screenshot.'}finally{captureBusy=false}}
const loadImage=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('The screenshot could not be decoded.'));i.src=src});
function renderCapture(){const box=$('#capture-tools');if(!box)return;box.innerHTML=capture.image?`<div class="capture-actions"><button type="button" id="highlight-mode" ${captureMode==='highlight'?'class="dark"':''}>Highlight</button><button type="button" id="crop-mode" ${captureMode==='crop'?'class="dark"':''}>Crop</button><button type="button" id="apply-crop" ${!cropRect?'disabled':''}>Apply crop</button><button type="button" id="undo-highlight" ${!capture.highlights.length?'disabled':''}>Undo highlight</button><button type="button" id="reset-crop">Full image</button><button type="button" id="remove-image">Remove image</button></div><p class="form-help">${captureMode==='crop'?'Drag a rectangle, then choose Apply crop.':'Drag over the exact area you want to highlight.'}</p><div class="capture-preview" id="capture-preview"><img draggable="false" src="${esc(capture.image)}" alt="Evidence screenshot being annotated">${capture.highlights.map(h=>`<span class="highlight" style="left:${h.x*100}%;top:${h.y*100}%;width:${h.w*100}%;height:${h.h*100}%"></span>`).join('')}${cropRect?rectHTML(cropRect,'crop-selection'):''}</div>`:'';
 if(!capture.image)return;
 $('#highlight-mode').onclick=()=>{captureMode='highlight';cropRect=null;renderCapture()};$('#crop-mode').onclick=()=>{captureMode='crop';renderCapture()};$('#undo-highlight').onclick=()=>{capture.highlights.pop();renderCapture()};$('#reset-crop').onclick=()=>{capture.image=capture.originalImage;capture.highlights=[];cropRect=null;renderCapture()};$('#remove-image').onclick=()=>{capture={image:'',originalImage:'',highlights:[]};renderCapture()};$('#apply-crop').onclick=async()=>{if(!cropRect||captureBusy)return;captureBusy=true;try{const img=await loadImage(capture.image),r=cropRect,c=document.createElement('canvas');c.width=Math.max(1,Math.round(r.w*img.width));c.height=Math.max(1,Math.round(r.h*img.height));c.getContext('2d').drawImage(img,r.x*img.width,r.y*img.height,r.w*img.width,r.h*img.height,0,0,c.width,c.height);capture.image=c.toDataURL('image/png');capture.highlights=capture.highlights.map(h=>{const x=Math.max(h.x,r.x),y=Math.max(h.y,r.y),x2=Math.min(h.x+h.w,r.x+r.w),y2=Math.min(h.y+h.h,r.y+r.h);return {x:(x-r.x)/r.w,y:(y-r.y)/r.h,w:(x2-x)/r.w,h:(y2-y)/r.h}}).filter(h=>h.w>0&&h.h>0);cropRect=null;renderCapture()}catch(err){$('#form-error').textContent=err.message}finally{captureBusy=false}};
 $('#capture-preview').onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();const el=e.currentTarget,b=el.getBoundingClientRect(),clamp=v=>Math.min(1,Math.max(0,v)),sx=clamp((e.clientX-b.left)/b.width),sy=clamp((e.clientY-b.top)/b.height);let r=null;const temp=document.createElement('span');temp.className=captureMode==='crop'?'crop-selection':'highlight';el.append(temp);el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{const x=clamp((ev.clientX-b.left)/b.width),y=clamp((ev.clientY-b.top)/b.height);r={x:Math.min(x,sx),y:Math.min(y,sy),w:Math.abs(x-sx),h:Math.abs(y-sy)};Object.assign(temp.style,{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'})};el.onpointerup=()=>{el.onpointermove=null;el.onpointerup=null;if(r&&r.w>.005&&r.h>.005){if(captureMode==='crop')cropRect=r;else capture.highlights.push(r)}renderCapture()};el.onpointercancel=()=>renderCapture()};
}
const rectHTML=(r,cls)=>`<span class="${cls}" style="left:${r.x*100}%;top:${r.y*100}%;width:${r.w*100}%;height:${r.h*100}%"></span>`;
function freePosition(){const vp=$('#viewport'),x0=Math.round(vp.scrollLeft/zoom+40),y0=Math.round(vp.scrollTop/zoom+90);for(let row=0;row<100;row++){for(let col=0;col<3;col++){const x=x0+col*370,y=y0+row*540;const overlaps=board.nodes.filter(active).some(n=>{const el=$(`#canvas [data-node="${CSS.escape(n.id)}"]`),w=el?.offsetWidth||300,h=el?.offsetHeight||400;return x<n.x+w+30&&x+330>n.x&&y<n.y+h+30&&y+450>n.y});if(!overlaps)return {x,y}}}return {x:x0,y:Math.max(0,...board.nodes.map(n=>n.y))+600}}
function inspectImage(id){const n=get(id);if(!n?.image)return;let dialog=$('#image-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='image-dialog';document.body.append(dialog)}let scale=1,original=false;const draw=()=>{dialog.innerHTML=`<div class="dialog-heading"><h2>${esc(n.text)}</h2><button data-close aria-label="Close screenshot">✕</button></div><div class="capture-actions"><button id="image-smaller">− Zoom</button><button id="image-larger">＋ Zoom</button>${n.originalImage?'<button id="image-context">'+(original?'Show annotated crop':'Show full context')+'</button>':''}</div><div class="image-scroll"><div style="width:${Math.round(100*scale)}%">${figure(original?{...n,image:n.originalImage,highlights:[]}:n)}</div></div>`;$('#image-smaller').onclick=()=>{scale=Math.max(.5,scale-.5);draw()};$('#image-larger').onclick=()=>{scale=Math.min(4,scale+.5);draw()};if($('#image-context'))$('#image-context').onclick=()=>{original=!original;draw()}};draw();dialog.showModal()}
document.addEventListener('paste',async e=>{if(!$('#editor').open||editorMode!=='card'||!$('#capture-tools'))return;const item=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith('image/'));if(item){e.preventDefault();await readImage(item.getAsFile())}});
function brief(){const lines=['# '+board.title,board.subtitle||'','Authored evidence map. Connections express the author’s reasoning; they do not independently verify claims.',''];for(const [i,n] of sequence().entries()){lines.push(`## ${i+1}. ${wording(n)}`,`Type: ${n.type}`,n.note||'');const related=board.links.filter(l=>l.to===n.id||l.from===n.id);if(n.type==='evidence')lines.push(n.quote?'Passage: '+n.quote:'',deepLink(n));for(const l of related){const other=get(l.from===n.id?l.to:l.from);if(!other)continue;lines.push(`${l.from===n.id?'Outgoing':'Incoming'} ${l.kind}${l.label?' ('+l.label+')':''}: ${wording(other)}`);if(other.type==='evidence')lines.push(other.quote?'Passage: '+other.quote:'',`Source: ${deepLink(other)}`,`Authority (author-assigned): ${other.tier||'Unreviewed'}; checked: ${other.checked||'not recorded'}`,other.image?'Screenshot and highlights included in the companion board file.':'')}lines.push('')}lines.push('## Other cards',...board.nodes.filter(n=>active(n)&&!sequence().some(s=>s.id===n.id)&&n.type!=='evidence').map(n=>`- [${n.type}] ${wording(n)}`),'','## Source register',...board.nodes.filter(n=>n.type==='evidence'&&active(n)).map(n=>`- ${n.text}: ${deepLink(n)} (checked ${n.checked||'not recorded'})`));return lines.filter(l=>l!==undefined).join('\n')}
$('#share').onclick=()=>{$('#brief-text').value=brief();$('#brief-dialog').showModal()};
$('#brief-dialog .dialog-actions').insertAdjacentHTML('afterbegin','<button id="export-reader">Interactive reader .html</button>');
$('#export-reader').onclick=async()=>{try{const [html,css,js,theme]=await Promise.all(['index.html','style.css','app.js','../shared/theme.css'].map(async p=>{const r=await fetch(p);if(!r.ok)throw new Error('Could not prepare the reader export.');return r.text()}));const publicBoard=structuredClone(board);publicBoard.nodes.forEach(n=>{delete n.originalImage;delete n.sourceCaptureId;delete n.sourcePageId;if(n.provenance?.anchor)delete n.provenance.anchor;});const end='</scr'+'ipt>';const seed=JSON.stringify(publicBoard).replace(/</g,'\\u003c');const out=html.replace('<link rel="stylesheet" href="../shared/theme.css">','').replace('<link rel="stylesheet" href="style.css">',()=>'<style>'+css+'\n'+theme+'</style>').replace('<script type="module" src="app.js">'+end,()=>'<script type="application/json" id="seed-board">'+seed+end+'<script type="module">'+js+end);download(filename()+'.reader.html',out,'text/html');notify('Interactive reader saved. It includes the visible screenshot crops.')}catch(err){notify(err.message)}};
async function copyText(text){try{await navigator.clipboard.writeText(text);notify('Copied')}catch{notify('Clipboard unavailable. Select and copy the text manually.')}}
$('#copy-brief').onclick=()=>copyText($('#brief-text').value);$('#download-brief').onclick=()=>download(filename()+'.md',$('#brief-text').value,'text/markdown');$('#print-brief').onclick=()=>{let el=$('#print-output');if(!el){el=document.createElement('pre');el.id='print-output';el.hidden=true;document.body.append(el)}el.textContent=$('#brief-text').value;window.print()};
window.addEventListener('beforeunload',e=>{if(unsaved){e.preventDefault();e.returnValue=''}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!e.target.matches('input,textarea,select,[contenteditable]')&&!$('dialog[open]')){e.preventDefault();undo(e.shiftKey)}if(e.target.matches('#canvas [data-node]')&&author&&!readerMode&&!walking&&!$('dialog[open]')&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const n=get(e.target.dataset.node),amount=e.shiftKey?50:10;delete n.auto;n.x=Math.max(0,n.x+(e.key==='ArrowLeft'?-amount:e.key==='ArrowRight'?amount:0));n.y=Math.max(0,n.y+(e.key==='ArrowUp'?-amount:e.key==='ArrowDown'?amount:0));persist();render();$(`#canvas [data-node="${CSS.escape(n.id)}"]`)?.focus()}});
if(readerMode){['#new-board','#import','#export','#export-reader','.segmented'].forEach(s=>$(s).hidden=true);$('#save-status').textContent='Shared reader · read only';}
else await initializeWorkspaceUI();
if(document.modelContext?.registerTool){const life=new AbortController();for(const tool of [{name:'read_evidence_board',title:'Read evidence board',description:'Read authored cards, relationships and walkthrough order without modifying the board.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({title:board.title,nodes:board.nodes.map(({image,originalImage,...n})=>({...n,hasScreenshot:!!image})),links:board.links,steps:board.steps})},{name:'inspect_evidence_card',title:'Inspect evidence card',description:'Select an existing card and reveal its details in the visible board. Does not edit content.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||typeof input.id!=='string'||!get(input.id))throw new Error('Unknown card ID');walking=false;tab='map';select(input.id,true);return {selected:input.id}}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true})}
// Narrow bridge for the optional modules (guided tour, local-AI drafting).
// They change the board only through these functions, so undo and saving
// behave exactly as they do for manual edits.
const api={get board(){return board},get session(){return session},workspace,get,uid,esc,notify,render,persist,freePosition,select,validateBoard,
 async flush(){await saveQueue;if(saveBlocked)throw new Error('Save your board file and reload before switching boards.');},
 setAuthor(v){author=!!v;render()},get tab(){return tab},allowedKinds,fitKind,setTab(t){tab=t;render()},openCard,showInbox,onRender(f){renderHooks.push(f)},commit(record=true){commitBoard(record)},typeLabel,startWalk(){walking=true;step=0;tab='map';render()},currentStep:()=>walking?sequence()[step]?.id:null,sequence:()=>sequence().map(n=>n.id)};
if(!readerMode){import('./guide.js').then(m=>m.init(api)).catch(e=>console.warn('Guide unavailable',e));import('./outline-editor.js').then(m=>m.init(api)).catch(e=>console.warn('Outline unavailable',e));import('./assist.js').then(m=>m.init(api)).catch(e=>console.warn('Local AI drafting unavailable',e));}
render();updateHistory();
if(!readerMode){
 const params=new URLSearchParams(location.search);
 if(params.get('author')){author=true;render();}
 if(params.get('walk')){walking=true;render();}
 if(params.get('focus')&&get(params.get('focus')))select(params.get('focus'),true);
 if(params.get('new')||params.get('tab')==='outline'){tab='outline';render();}
 if(params.get('inbox'))await showInbox();
 if(params.get('captureError'))notify(params.get('captureError'));
}


async function initializeWorkspaceUI(){
  window.history.replaceState(null,'','?'+new URLSearchParams({...Object.fromEntries(new URLSearchParams(location.search)),j:session.journey.id,b:session.record.id}));
  $('.brand').href='../journey/journey.html?j='+encodeURIComponent(session.journey.id);
  $('.brand').innerHTML='<span class="brandmark">▧</span> THE THINGS WE LEARNED';
  $('.brand').setAttribute('aria-label','Return to browsing trail');
  $('.topline').insertAdjacentHTML('afterend','<nav class="workspace-nav"><a id="trail-link">Browsing trail</a><span aria-current="page">Evidence board</span><label for="board-picker">Argument</label><select id="board-picker"></select><button id="inbox-button">Evidence inbox</button></nav>');
  $('#trail-link').href='../journey/journey.html?j='+encodeURIComponent(session.journey.id);
  refreshPicker();
  $('#board-picker').onchange=async e=>{const id=e.target.value;await saveQueue;if(saveBlocked){e.target.value=session.record.id;notify('Save your board file and reload before switching arguments.');return;}location.href='?'+new URLSearchParams({j:session.journey.id,b:id});};
  $('#inbox-button').onclick=()=>showInbox();
  $('#save-status').textContent='Saved in '+session.journey.name;
  globalThis.chrome?.runtime?.onMessage?.addListener(msg=>{if(msg.type==='trail-updated'&&msg.journeyId===session.journey.id)$('#inbox-button').textContent='Evidence inbox · updated';});
}
function refreshPicker(){if(!$('#board-picker'))return;$('#board-picker').innerHTML=session.boards.map(b=>`<option value="${esc(b.id)}" ${b.id===session.record.id?'selected':''}>${esc((t=>t==='What am I trying to establish?'?'Untitled question':t)(b.id===session.record.id?board.title:b.content.title))}</option>`).join('');}
async function showInbox(){
  let dialog=$('#inbox-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='inbox-dialog';document.body.append(dialog);}
  dialog.innerHTML='<div class="dialog-heading"><h2>Evidence inbox</h2><button data-close aria-label="Close evidence inbox">✕</button></div><p>Loading captured passages…</p>';dialog.showModal();
  try{
    const captures=await workspace.inbox(session.journey.id);
    dialog.innerHTML=`<div class="dialog-heading"><h2>Evidence inbox</h2><button data-close aria-label="Close evidence inbox">✕</button></div><p class="form-help">Select text on a page and right-click → Add passage to evidence board. Use Capture screenshot as evidence for a visible-page snapshot. Existing highlights are also available here.</p><label class="form-label" for="inbox-target">Attach new evidence to a claim (optional)</label><select id="inbox-target"><option value="">Add without a connection</option>${board.nodes.filter(n=>['claim','conclusion','gap'].includes(n.type)).map(n=>`<option value="${esc(n.id)}" ${selected===n.id?'selected':''}>${esc(n.text)}</option>`).join('')}</select><div class="inbox-items">${captures.map(c=>`<article class="inbox-item"><p class="eyebrow">${esc(domain(c.url))} · ${esc(c.view||'original')}</p><h3>${esc(c.title)}</h3>${c.quote?`<blockquote>${esc(c.quote)}</blockquote>`:''}${c.note?`<p class="form-help">${esc(c.note)}</p>`:''}<p class="form-help">${esc(new Date(c.capturedAt).toLocaleString())}${c.image?' · Screenshot included':''}</p><button data-pin-capture="${esc(c.id)}" ${board.nodes.some(n=>n.sourceCaptureId===c.id)?'disabled':''}>${board.nodes.some(n=>n.sourceCaptureId===c.id)?'Already on this board':c.kind==='note'?'Add as a thought':'Add & edit evidence'}</button></article>`).join('')||'<p class="empty">No captured evidence yet. You can also add evidence manually from the Author toolbar.</p>'}</div>`;
    dialog.querySelectorAll('[data-pin-capture]').forEach(button=>button.onclick=()=>{
      if(board.nodes.length>=500){notify('This board has reached the 500-card limit.');return;}
      const capture=captures.find(c=>c.id===button.dataset.pinCapture);if(!capture)return;
      const card=capture.kind==='note'?workspace.noteCard(capture,freePosition()):workspace.evidenceCard(capture,freePosition());board.nodes.push(card);
      const target=$('#inbox-target').value;if(target)board.links.push({id:uid(),from:card.id,to:target,kind:get(target)?.type==='gap'?'questions':'supports',label:''});
      selected=card.id;author=true;persist();dialog.close();render();if(card.type==='evidence')openCard('evidence',card.id);
    });
    $('#inbox-button').textContent='Evidence inbox';
  }catch(error){dialog.querySelector('p').textContent=error.message;}
}
